/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Akbar
 */
public class rekapanlaporan extends javax.swing.JFrame {

    /**
     * Creates new form rekapanlaporan
     */
    public rekapanlaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rekaptamu = new javax.swing.JButton();
        rekappesdik = new javax.swing.JButton();
        rekapguru = new javax.swing.JButton();
        rekapkunjungan = new javax.swing.JButton();
        rekapizinpesdik = new javax.swing.JButton();
        rekapizinguru = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuutama = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        pendataan = new javax.swing.JMenu();
        tamu = new javax.swing.JMenuItem();
        siswa = new javax.swing.JMenuItem();
        guru = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        kunjungan = new javax.swing.JMenuItem();
        izinsiswa = new javax.swing.JMenuItem();
        izinguru = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        lapparameter = new javax.swing.JMenuItem();
        rekapanlap = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REKAPAN LAPORAN SMKN 8 JAKARTA");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/SMK_Negeri_8_Jakarta (2).png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setFont(new java.awt.Font("Gobold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SMK_Negeri_8_Jakarta (2).png"))); // NOI18N
        jLabel2.setText("REKAPAN LAPORAN SMKN 8 JAKARTA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Gobold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~MENU REKAPAN LAPORAN~");

        rekaptamu.setBackground(new java.awt.Color(51, 153, 255));
        rekaptamu.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekaptamu.setText("REKAPAN TAMU");
        rekaptamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekaptamuActionPerformed(evt);
            }
        });

        rekappesdik.setBackground(new java.awt.Color(51, 153, 255));
        rekappesdik.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekappesdik.setText("REKAPAN PESERTA DIDIK");
        rekappesdik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekappesdikActionPerformed(evt);
            }
        });

        rekapguru.setBackground(new java.awt.Color(51, 153, 255));
        rekapguru.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekapguru.setText("REKAPAN GURU");
        rekapguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapguruActionPerformed(evt);
            }
        });

        rekapkunjungan.setBackground(new java.awt.Color(51, 153, 255));
        rekapkunjungan.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekapkunjungan.setText("REKAPAN KUNJUNGAN");
        rekapkunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapkunjunganActionPerformed(evt);
            }
        });

        rekapizinpesdik.setBackground(new java.awt.Color(51, 153, 255));
        rekapizinpesdik.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekapizinpesdik.setText("REKAPAN IZIN PESDIK");
        rekapizinpesdik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapizinpesdikActionPerformed(evt);
            }
        });

        rekapizinguru.setBackground(new java.awt.Color(51, 153, 255));
        rekapizinguru.setFont(new java.awt.Font("Gobold", 0, 18)); // NOI18N
        rekapizinguru.setText("REKAPAN IZIN GURU");
        rekapizinguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapizinguruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rekapguru, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rekapizinguru, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rekappesdik, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rekapizinpesdik, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rekaptamu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rekapkunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rekaptamu)
                    .addComponent(rekapkunjungan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rekappesdik)
                    .addComponent(rekapizinpesdik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rekapguru)
                    .addComponent(rekapizinguru))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Gobold", 0, 14)); // NOI18N

        jMenu1.setText("Main Menu");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuutama.setText("Menu Utama");
        menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuutamaActionPerformed(evt);
            }
        });
        jMenu1.add(menuutama);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        pendataan.setText("Pendataan");
        pendataan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tamu.setText("Data Tamu");
        tamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamuActionPerformed(evt);
            }
        });
        pendataan.add(tamu);

        siswa.setText("Data Peserta Didik");
        siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaActionPerformed(evt);
            }
        });
        pendataan.add(siswa);

        guru.setText("Data Guru");
        guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guruActionPerformed(evt);
            }
        });
        pendataan.add(guru);

        jMenuBar1.add(pendataan);

        jMenu3.setText("Pelayanan");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        kunjungan.setText("Kunjungan");
        kunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunjunganActionPerformed(evt);
            }
        });
        jMenu3.add(kunjungan);

        izinsiswa.setText("Form Izin Pesdik");
        izinsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinsiswaActionPerformed(evt);
            }
        });
        jMenu3.add(izinsiswa);

        izinguru.setText("Form Izin Guru");
        izinguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinguruActionPerformed(evt);
            }
        });
        jMenu3.add(izinguru);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lapparameter.setText("Laporan Parameter");
        lapparameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapparameterActionPerformed(evt);
            }
        });
        jMenu4.add(lapparameter);

        rekapanlap.setText("Rekapan Laporan");
        rekapanlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapanlapActionPerformed(evt);
            }
        });
        jMenu4.add(rekapanlap);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(563, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rekaptamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekaptamuActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "C:\\Users\\Akbar\\Documents\\"
                + "NetBeansProjects\\Resepsionis SMKN8 Jakarta\\"
                + "src\\laporan\\rekaptamu.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekaptamuActionPerformed

    private void rekappesdikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekappesdikActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "src/laporan/rekappesdik.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekappesdikActionPerformed

    private void rekapguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapguruActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "src/laporan/rekapguru.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekapguruActionPerformed

    private void rekapkunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapkunjunganActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "src/laporan/rekapkunjungan.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekapkunjunganActionPerformed

    private void rekapizinpesdikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapizinpesdikActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "src/laporan/rekapizinpesdik.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekapizinpesdikActionPerformed

    private void rekapizinguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapizinguruActionPerformed
        // TODO add your handling code here:
        try{
        String namaFile = "src/laporan/rekapizinguru.jasper";
        Connection conn = new koneksi().connect();
        HashMap parameter = new HashMap();
        File report_file = new File(namaFile);
        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
        JasperViewer.viewReport(jasperPrint, false); //coba
        JasperViewer.setDefaultLookAndFeelDecorated(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    }//GEN-LAST:event_rekapizinguruActionPerformed

    private void menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuutamaActionPerformed
        // TODO add your handling code here:
        new tampilan.menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuutamaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new tampilan.login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void tamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamuActionPerformed
        // TODO add your handling code here:
        new tampilan.tamu().setVisible(true);
        dispose();
    }//GEN-LAST:event_tamuActionPerformed

    private void siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaActionPerformed
        // TODO add your handling code here:
        new tampilan.pesdik().setVisible(true);
        dispose();
    }//GEN-LAST:event_siswaActionPerformed

    private void guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruActionPerformed
        // TODO add your handling code here:
        new tampilan.guru().setVisible(true);
        dispose();
    }//GEN-LAST:event_guruActionPerformed

    private void kunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kunjunganActionPerformed
        // TODO add your handling code here:
        new tampilan.kunjungan().setVisible(true);
        dispose();
    }//GEN-LAST:event_kunjunganActionPerformed

    private void izinsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinsiswaActionPerformed
        // TODO add your handling code here:
        new tampilan.izinpesertadidik().setVisible(true);
        dispose();
    }//GEN-LAST:event_izinsiswaActionPerformed

    private void izinguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinguruActionPerformed
        // TODO add your handling code here:
        new tampilan.izinguru().setVisible(true);
        dispose();
    }//GEN-LAST:event_izinguruActionPerformed

    private void lapparameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapparameterActionPerformed
        // TODO add your handling code here:
        new tampilan.laporanparameter().setVisible(true);
        dispose();
    }//GEN-LAST:event_lapparameterActionPerformed

    private void rekapanlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapanlapActionPerformed
        // TODO add your handling code here:
        new tampilan.rekapanlaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_rekapanlapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rekapanlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rekapanlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rekapanlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rekapanlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rekapanlaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem guru;
    private javax.swing.JMenuItem izinguru;
    private javax.swing.JMenuItem izinsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem kunjungan;
    private javax.swing.JMenuItem lapparameter;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem menuutama;
    private javax.swing.JMenu pendataan;
    private javax.swing.JMenuItem rekapanlap;
    private javax.swing.JButton rekapguru;
    private javax.swing.JButton rekapizinguru;
    private javax.swing.JButton rekapizinpesdik;
    private javax.swing.JButton rekapkunjungan;
    private javax.swing.JButton rekappesdik;
    private javax.swing.JButton rekaptamu;
    private javax.swing.JMenuItem siswa;
    private javax.swing.JMenuItem tamu;
    // End of variables declaration//GEN-END:variables
}
